### ISSUE TITLE
[stock] Thrashing, stalls, higher latency with swap use

### ISSUE THREAD

**Issue by zachariasmaladroit** [zachariasmaladroit/android_kernel_sony_msm8994_kitakami_r2#4]
There's noticeable stalls, higher latency and lagginess throughout the ROM when swap is being used, I remember @GreyLeshy mentioning something like that one XDA

needs investigating on how to mitigate this, increase throughput on swap (zram!) and lower overhead

Not sure how or why it's triggered by BreachKernel, but pretty soon-ish it's there (after booting the ROM !),

behavior is as follows:

after waking up from sleep/standby (screen off) - the UI is pretty laggy, apps take quite a noticeable delay until they are launched (or the system even reacts to this) ...

I recall this being mentioned a few years ago on lkml by Mike Galbraith on CFS & his desktop w.r.t. to swap (or hibernate)

**Comment by kernelOfTruth** [comment]
Seems swap isn't worth the effort ...

with improved mm subsystem, vmalloc, reclaim, memcg & friends with zram turned off experience is much more consistent

**Comment by zachariasmaladroit** [comment]
Seems swap isn't worth the effort ...

with improved mm subsystem, vmalloc, reclaim, memcg & friends with zram turned off experience is much more consistent
